version: "3.2"
services:
  redbot:
    container_name: redbot
    image: redbot
    restart: unless-stopped
    volumes:
      - ./redbot:/data
    environment:
      - TOKEN=
      - PREFIX=
      - TZ=America/Sao_Paulo
      - PUID=1000
